name: Build DATUM Gateway

on:
    schedule:
        - cron: '0 0 1 * *'
    push:
    pull_request:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu:latest
          - ubuntu:22.04
        config:
          - cmake_args: "-DENABLE_API=ON"
            extra_deps: "libmicrohttpd-dev"
          - cmake_args: "-DENABLE_API=OFF"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build inside Docker
        run: |
          CMD="set -ex
            apt update
            apt install -y build-essential cmake libcurl4-openssl-dev libjansson-dev libsodium-dev pkgconf ${{ matrix.config.extra_deps }}
            git config --global --add safe.directory /workspace
            mkdir -p build
            cd build
            cmake /workspace ${{ matrix.config.cmake_args }}
            make -j\$(nproc)
          "
          docker run \
            -v "${{ github.workspace }}:/workspace":ro \
            "${{ matrix.os }}" \
            /bin/sh -c "${CMD}"
