name: Build DATUM Gateway

on:
    schedule:
        - cron: '0 0 1 * *'
    push:
    pull_request:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-22.04
        config:
          - cmake_args: "-DENABLE_API=ON"
            extra_deps: "libmicrohttpd-dev"
          - cmake_args: "-DENABLE_API=OFF"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create build directory
        run: mkdir -p build
        
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libjansson-dev libsodium-dev ${{ matrix.config.extra_deps }}
      
      - name: Build DATUM Gateway
        run: |
          cd build
          cmake .. ${{ matrix.config.cmake_args }}
          make -j$(nproc)
